# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgB.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 653)
        font = QtGui.QFont()
        font.setPointSize(13)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(550, 40, 91, 81))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 10, 51, 20))
        self.label.setObjectName("label")
        self.txmaxB = QtWidgets.QLineEdit(Dialog)
        self.txmaxB.setGeometry(QtCore.QRect(310, 30, 81, 25))
        self.txmaxB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txmaxB.setObjectName("txmaxB")
        self.btMakeB = QtWidgets.QPushButton(Dialog)
        self.btMakeB.setGeometry(QtCore.QRect(310, 60, 89, 61))
        self.btMakeB.setObjectName("btMakeB")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 160, 591, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.oglayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.oglayout.setContentsMargins(0, 0, 0, 0)
        self.oglayout.setObjectName("oglayout")
        self.listdir = QtWidgets.QListWidget(Dialog)
        self.listdir.setGeometry(QtCore.QRect(410, 40, 121, 71))
        self.listdir.setObjectName("listdir")
        item = QtWidgets.QListWidgetItem()
        self.listdir.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listdir.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listdir.addItem(item)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(410, 10, 161, 17))
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 161, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.menuLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.menuLayout.setContentsMargins(0, 0, 0, 0)
        self.menuLayout.setObjectName("menuLayout")
        self.lbinfo = QtWidgets.QLabel(Dialog)
        self.lbinfo.setGeometry(QtCore.QRect(130, 140, 511, 17))
        self.lbinfo.setObjectName("lbinfo")
        self.opcBApp = QtWidgets.QRadioButton(Dialog)
        self.opcBApp.setGeometry(QtCore.QRect(170, 30, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.opcBApp.setFont(font)
        self.opcBApp.setChecked(True)
        self.opcBApp.setObjectName("opcBApp")
        self.opcBmagpy = QtWidgets.QRadioButton(Dialog)
        self.opcBmagpy.setGeometry(QtCore.QRect(170, 70, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.opcBmagpy.setFont(font)
        self.opcBmagpy.setObjectName("opcBmagpy")

        self.retranslateUi(Dialog)
        self.listdir.setCurrentRow(2)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.opcBApp.toggled['bool'].connect(self.listdir.setVisible)
        self.opcBApp.toggled['bool'].connect(self.label_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "non uniform Magnetic field"))
        self.label.setText(_translate("Dialog", "max B"))
        self.txmaxB.setText(_translate("Dialog", "5000.0"))
        self.btMakeB.setText(_translate("Dialog", "Make B"))
        __sortingEnabled = self.listdir.isSortingEnabled()
        self.listdir.setSortingEnabled(False)
        item = self.listdir.item(0)
        item.setText(_translate("Dialog", "dir X"))
        item = self.listdir.item(1)
        item.setText(_translate("Dialog", "dir Y"))
        item = self.listdir.item(2)
        item.setText(_translate("Dialog", "dir Z"))
        self.listdir.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Dialog", "magnetic flow in"))
        self.lbinfo.setText(_translate("Dialog", "info"))
        self.opcBApp.setToolTip(_translate("Dialog", "<html><head/><body><p>very simple magnetic field</p></body></html>"))
        self.opcBApp.setText(_translate("Dialog", "B from App"))
        self.opcBmagpy.setToolTip(_translate("Dialog", "<html><head/><body><p>B created with magpylib in Z (much better than from App for Gerlach test)</p></body></html>"))
        self.opcBmagpy.setText(_translate("Dialog", "B  Magpy in Z"))

