# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgogl.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DlgOgl(object):
    def setupUi(self, DlgOgl):
        DlgOgl.setObjectName("DlgOgl")
        DlgOgl.resize(423, 300)
        font = QtGui.QFont()
        font.setPointSize(13)
        DlgOgl.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgOgl)
        self.buttonBox.setGeometry(QtCore.QRect(50, 250, 261, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(DlgOgl)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 341, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 111, 17))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txumbral = QtWidgets.QLineEdit(self.groupBox)
        self.txumbral.setGeometry(QtCore.QRect(130, 50, 121, 25))
        font = QtGui.QFont()
        font.setItalic(False)
        self.txumbral.setFont(font)
        self.txumbral.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txumbral.setObjectName("txumbral")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 90, 221, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.txminPoints = QtWidgets.QLineEdit(self.groupBox_2)
        self.txminPoints.setGeometry(QtCore.QRect(70, 30, 81, 25))
        font = QtGui.QFont()
        font.setItalic(False)
        self.txminPoints.setFont(font)
        self.txminPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txminPoints.setObjectName("txminPoints")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 41, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txmaxpoints = QtWidgets.QLineEdit(self.groupBox_2)
        self.txmaxpoints.setGeometry(QtCore.QRect(70, 60, 81, 25))
        font = QtGui.QFont()
        font.setItalic(False)
        self.txmaxpoints.setFont(font)
        self.txmaxpoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txmaxpoints.setObjectName("txmaxpoints")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 41, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DlgOgl)
        self.buttonBox.accepted.connect(DlgOgl.accept)
        self.buttonBox.rejected.connect(DlgOgl.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgOgl)

    def retranslateUi(self, DlgOgl):
        _translate = QtCore.QCoreApplication.translate
        DlgOgl.setWindowTitle(_translate("DlgOgl", "OpenGL ( render DIrac 3D np array )"))
        self.groupBox.setTitle(_translate("DlgOgl", "extract some points from probability"))
        self.label.setText(_translate("DlgOgl", "min umbral"))
        self.txumbral.setToolTip(_translate("DlgOgl", "<html><head/><body><p><span style=\" font-size:10pt;\">Min percent from the max probabilty to include a point from psi probability. This can change autmatically change if number os points are not in the below range</span></p></body></html>"))
        self.txumbral.setText(_translate("DlgOgl", "0.0002"))
        self.groupBox_2.setTitle(_translate("DlgOgl", "number of points (range)"))
        self.txminPoints.setToolTip(_translate("DlgOgl", "<html><head/><body><p><span style=\" font-size:10pt;\">min number of points to extract from numpy 3D array</span></p></body></html>"))
        self.txminPoints.setText(_translate("DlgOgl", "800"))
        self.label_2.setText(_translate("DlgOgl", "min"))
        self.txmaxpoints.setToolTip(_translate("DlgOgl", "<html><head/><body><p><span style=\" font-size:10pt;\">max number of points to extract from numpy 3D array</span></p></body></html>"))
        self.txmaxpoints.setText(_translate("DlgOgl", "3000"))
        self.label_3.setText(_translate("DlgOgl", "max"))

