# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwnd.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 678)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxPos = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPos.setGeometry(QtCore.QRect(30, 10, 121, 151))
        self.groupBoxPos.setObjectName("groupBoxPos")
        self.label_2 = QtWidgets.QLabel(self.groupBoxPos)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 21, 17))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBoxPos)
        self.label.setGeometry(QtCore.QRect(20, 30, 21, 17))
        self.label.setObjectName("label")
        self.txX1 = QtWidgets.QLineEdit(self.groupBoxPos)
        self.txX1.setGeometry(QtCore.QRect(40, 60, 51, 25))
        self.txX1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txX1.setObjectName("txX1")
        self.txY1 = QtWidgets.QLineEdit(self.groupBoxPos)
        self.txY1.setGeometry(QtCore.QRect(40, 30, 51, 25))
        self.txY1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txY1.setObjectName("txY1")
        self.label_5 = QtWidgets.QLabel(self.groupBoxPos)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 31, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBoxPos)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 31, 20))
        self.label_6.setObjectName("label_6")
        self.txKY1 = QtWidgets.QLineEdit(self.groupBoxPos)
        self.txKY1.setGeometry(QtCore.QRect(40, 90, 61, 25))
        self.txKY1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txKY1.setObjectName("txKY1")
        self.txKX1 = QtWidgets.QLineEdit(self.groupBoxPos)
        self.txKX1.setGeometry(QtCore.QRect(40, 120, 61, 25))
        self.txKX1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txKX1.setObjectName("txKX1")
        self.btPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btPlay.setGeometry(QtCore.QRect(530, 480, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btPlay.setFont(font)
        self.btPlay.setObjectName("btPlay")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 380, 31, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.txN = QtWidgets.QLineEdit(self.centralwidget)
        self.txN.setGeometry(QtCore.QRect(520, 400, 41, 25))
        self.txN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txN.setObjectName("txN")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 380, 31, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.txL = QtWidgets.QLineEdit(self.centralwidget)
        self.txL.setGeometry(QtCore.QRect(600, 400, 41, 25))
        self.txL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txL.setObjectName("txL")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 440, 31, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.txDT = QtWidgets.QLineEdit(self.centralwidget)
        self.txDT.setGeometry(QtCore.QRect(560, 440, 71, 25))
        self.txDT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txDT.setObjectName("txDT")
        self.groupBoxPos_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxPos_2.setGeometry(QtCore.QRect(170, 10, 121, 151))
        self.groupBoxPos_2.setObjectName("groupBoxPos_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxPos_2)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 21, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxPos_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 21, 17))
        self.label_4.setObjectName("label_4")
        self.txX2 = QtWidgets.QLineEdit(self.groupBoxPos_2)
        self.txX2.setGeometry(QtCore.QRect(40, 60, 51, 25))
        self.txX2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txX2.setObjectName("txX2")
        self.txY2 = QtWidgets.QLineEdit(self.groupBoxPos_2)
        self.txY2.setGeometry(QtCore.QRect(40, 30, 51, 25))
        self.txY2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txY2.setObjectName("txY2")
        self.label_10 = QtWidgets.QLabel(self.groupBoxPos_2)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 31, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxPos_2)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 31, 20))
        self.label_11.setObjectName("label_11")
        self.txKY2 = QtWidgets.QLineEdit(self.groupBoxPos_2)
        self.txKY2.setGeometry(QtCore.QRect(40, 90, 61, 25))
        self.txKY2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txKY2.setObjectName("txKY2")
        self.txKX2 = QtWidgets.QLineEdit(self.groupBoxPos_2)
        self.txKX2.setGeometry(QtCore.QRect(40, 120, 61, 25))
        self.txKX2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txKX2.setObjectName("txKX2")
        self.lbogl = QtWidgets.QLabel(self.centralwidget)
        self.lbogl.setGeometry(QtCore.QRect(20, 220, 451, 441))
        self.lbogl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbogl.setText("")
        self.lbogl.setObjectName("lbogl")
        self.btReplay = QtWidgets.QPushButton(self.centralwidget)
        self.btReplay.setGeometry(QtCore.QRect(550, 550, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btReplay.setFont(font)
        self.btReplay.setObjectName("btReplay")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 0, 391, 211))
        self.groupBox.setObjectName("groupBox")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 21, 17))
        self.label_16.setObjectName("label_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 21, 17))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 21, 17))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 21, 17))
        self.label_14.setObjectName("label_14")
        self.txspin0r = QtWidgets.QLineEdit(self.groupBox)
        self.txspin0r.setGeometry(QtCore.QRect(30, 40, 131, 25))
        self.txspin0r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin0r.setObjectName("txspin0r")
        self.lbbloch1 = QtWidgets.QLabel(self.groupBox)
        self.lbbloch1.setGeometry(QtCore.QRect(10, 160, 361, 17))
        self.lbbloch1.setObjectName("lbbloch1")
        self.lbbloch2 = QtWidgets.QLabel(self.groupBox)
        self.lbbloch2.setGeometry(QtCore.QRect(10, 190, 361, 17))
        self.lbbloch2.setObjectName("lbbloch2")
        self.txspin0i = QtWidgets.QLineEdit(self.groupBox)
        self.txspin0i.setGeometry(QtCore.QRect(180, 40, 131, 25))
        self.txspin0i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin0i.setObjectName("txspin0i")
        self.txspin1i = QtWidgets.QLineEdit(self.groupBox)
        self.txspin1i.setGeometry(QtCore.QRect(180, 70, 131, 25))
        self.txspin1i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin1i.setObjectName("txspin1i")
        self.txspin1r = QtWidgets.QLineEdit(self.groupBox)
        self.txspin1r.setGeometry(QtCore.QRect(30, 70, 131, 25))
        self.txspin1r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin1r.setObjectName("txspin1r")
        self.txspin3i = QtWidgets.QLineEdit(self.groupBox)
        self.txspin3i.setGeometry(QtCore.QRect(180, 130, 131, 25))
        self.txspin3i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin3i.setObjectName("txspin3i")
        self.txspin3r = QtWidgets.QLineEdit(self.groupBox)
        self.txspin3r.setGeometry(QtCore.QRect(30, 130, 131, 25))
        self.txspin3r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin3r.setObjectName("txspin3r")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(200, 20, 91, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(50, 20, 91, 17))
        self.label_18.setObjectName("label_18")
        self.btLoadSpin = QtWidgets.QPushButton(self.groupBox)
        self.btLoadSpin.setGeometry(QtCore.QRect(320, 50, 71, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btLoadSpin.sizePolicy().hasHeightForWidth())
        self.btLoadSpin.setSizePolicy(sizePolicy)
        self.btLoadSpin.setObjectName("btLoadSpin")
        self.txspin2i = QtWidgets.QLineEdit(self.centralwidget)
        self.txspin2i.setGeometry(QtCore.QRect(470, 100, 131, 25))
        self.txspin2i.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin2i.setObjectName("txspin2i")
        self.txspin2r = QtWidgets.QLineEdit(self.centralwidget)
        self.txspin2r.setGeometry(QtCore.QRect(320, 100, 131, 25))
        self.txspin2r.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txspin2r.setObjectName("txspin2r")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 250, 211, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioBall = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBall.setGeometry(QtCore.QRect(20, 30, 181, 23))
        self.radioBall.setObjectName("radioBall")
        self.radioBhalf = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioBhalf.setGeometry(QtCore.QRect(20, 60, 191, 23))
        self.radioBhalf.setChecked(True)
        self.radioBhalf.setObjectName("radioBhalf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pauli two particles in magnetic field (4x4 spinnors rotations) "))
        self.groupBoxPos.setTitle(_translate("MainWindow", "particle 1"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.label.setText(_translate("MainWindow", "X"))
        self.txX1.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txX1.setText(_translate("MainWindow", "0.3"))
        self.txY1.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txY1.setText(_translate("MainWindow", "-0.7"))
        self.label_5.setText(_translate("MainWindow", "k Y"))
        self.label_6.setText(_translate("MainWindow", "k X"))
        self.txKY1.setText(_translate("MainWindow", "10"))
        self.txKX1.setText(_translate("MainWindow", "0"))
        self.btPlay.setText(_translate("MainWindow", "Play"))
        self.label_7.setText(_translate("MainWindow", "N"))
        self.txN.setToolTip(_translate("MainWindow", "<html><head/><body><p>number of psi points</p></body></html>"))
        self.txN.setText(_translate("MainWindow", "32"))
        self.label_8.setText(_translate("MainWindow", "L"))
        self.txL.setToolTip(_translate("MainWindow", "<html><head/><body><p>space length in atomic units</p></body></html>"))
        self.txL.setText(_translate("MainWindow", "2"))
        self.label_9.setText(_translate("MainWindow", "DT"))
        self.txDT.setToolTip(_translate("MainWindow", "time step in atomic units"))
        self.txDT.setText(_translate("MainWindow", "0.001"))
        self.groupBoxPos_2.setTitle(_translate("MainWindow", "particle 2"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.txX2.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txX2.setText(_translate("MainWindow", "-0.4"))
        self.txY2.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txY2.setText(_translate("MainWindow", "0.7"))
        self.label_10.setText(_translate("MainWindow", "k Y"))
        self.label_11.setText(_translate("MainWindow", "k X"))
        self.txKY2.setText(_translate("MainWindow", "-10"))
        self.txKX2.setText(_translate("MainWindow", "0"))
        self.btReplay.setText(_translate("MainWindow", "RePlay"))
        self.groupBox.setTitle(_translate("MainWindow", "initial spin (state vector)"))
        self.label_16.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "2"))
        self.label_14.setText(_translate("MainWindow", "1"))
        self.txspin0r.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin0r.setText(_translate("MainWindow", "0"))
        self.lbbloch1.setText(_translate("MainWindow", "bloch 1"))
        self.lbbloch2.setText(_translate("MainWindow", "bloch 2"))
        self.txspin0i.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin0i.setText(_translate("MainWindow", "0"))
        self.txspin1i.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin1i.setText(_translate("MainWindow", "0"))
        self.txspin1r.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin1r.setText(_translate("MainWindow", "0"))
        self.txspin3i.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin3i.setText(_translate("MainWindow", "0"))
        self.txspin3r.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin3r.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "imaginary"))
        self.label_18.setText(_translate("MainWindow", "real"))
        self.btLoadSpin.setToolTip(_translate("MainWindow", "load a spin state vector file (npy with 4 complex numbers that forms a state vector)"))
        self.btLoadSpin.setText(_translate("MainWindow", "\n"
"Load\n"
"spin\n"
"file\n"
""))
        self.txspin2i.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin2i.setText(_translate("MainWindow", "0"))
        self.txspin2r.setToolTip(_translate("MainWindow", "<html><head/><body><p>from -0.8 to 0.8</p></body></html>"))
        self.txspin2r.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Magnetic potential spinnors"))
        self.radioBall.setToolTip(_translate("MainWindow", "<html><head/><body><p>apply B spinnors to all space(both particles)</p></body></html>"))
        self.radioBall.setText(_translate("MainWindow", "2 particles (all space)"))
        self.radioBhalf.setToolTip(_translate("MainWindow", "<html><head/><body><p>Apply B spinnos to only the right half space( one particle)</p></body></html>"))
        self.radioBhalf.setText(_translate("MainWindow", "1 particle (half right space)"))

